var LawfulClericPatrons = [
    "The Holy Angels",
    "All the Saints",
    "The Glorious Apostles",
    "The Illustrious Patriarchs",
    "The Noble Prophets",
    "The Faithful Confessors",
    "The Army of Martyrs",
    "The Flawless Virgins",
    "The Bright Seraphim",
    "The Glorious Cherubim",
    "The Mighty Thrones",
    "The Heavenly Powers",
    "Holy Metatron",
    "The Archangel Ananiel",
    "The Archangel Suriel",
    "The Archangel Zadkiel",
    "The Archangel Phanuel",
    "The Archangel Camael",
    "The Archangel Jophiel",
    "The Archangel Zadkiel",
];
var ChaoticClericPatrons = [
    "The Undying Wyrm",
    "The Titans of Tartarus",
    "The Nefarious Powers",
    "Mater Chaos",
    "The Unhallows",
    "The Other Gods",
    "The Outer Gods",
    "The Great Old Ones",
    "The Abyssal Powers",
    "The Dominations of Hel",
    "The Desolating Sacrilege",
    "The Defiled",
    "Infernal Abasements",
    "The Abomination of the Sidonians",
    "The Abomination of Amalekites",
    "The Abominations of Ammonites",
    "The Abominations of the Hittites",
    "The Abomination of Perizzites",
    "The Abomination of the Jebusites",
    "The Abominations of Hivites",
];