var FightingManTitles = [
    "Veteran",
    "Warrior",
    "Swordsman",
    "Hero",
    "Swashbuckler",
    "Myrmidon",
    "Champion",
    "Super-hero",
    "Super-hero",
    "Super-hero",
    "Super-hero",
    "Legend",
];
var AmazonTitles = [
    "Veteran",
    "Warrioress",
    "Swordsdame",
    "Heroine",
    "Swashbucklerette",
    "Myrmidonna",
    "Championess",
    "Super-heroine",
    "Super-heroine",
    "Super-heroine",
    "Super-heroine",
    "Legend",
];